### ISSUE TITLE
Doc update to include monitors

### ISSUE THREAD

**Issue by santanusinha** [flipkart-incubator/ranger#12]
Update document to include details about monitors.

**Comment by santanusinha** [comment]
Bump!!

**Comment by Tushar-Naik** [comment]
Oh yes. Had sent it some time back. PR19

**Comment by santanusinha** [comment]
Separate the doc update
i think i will close the other one, will break too many stuff all over the place
incline monitors are healthchecks anyways.

A cleaner implementation would be Monitors for async checks only.
Healthchecks for inline checks. But anyways I think healthcheck should be there. So sepearate the doc changes and send another PR. I will merge. I will close the existing one once you are done.

**Comment by Tushar-Naik** [comment]
done. have updated the same PR
